// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using XamMvvmAndWebServices;

namespace XamMvvmAndWebServices
{
    public static partial class SetupExtensions
    {
        /// <param name='operations'>
        /// Reference to the XamMvvmAndWebServices.ISetup.
        /// </param>
        public static string GetSetup(this ISetup operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((ISetup)s).GetSetupAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the XamMvvmAndWebServices.ISetup.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> GetSetupAsync(this ISetup operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.GetSetupWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
