// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using XamFormsMvvmAndRESTServices;

namespace XamFormsMvvmAndRESTServices
{
    public partial class XamarinMVVMSampleWebAPIService : ServiceClient<XamarinMVVMSampleWebAPIService>, IXamarinMVVMSampleWebAPIService
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private ICourses _courses;
        
        public virtual ICourses Courses
        {
            get { return this._courses; }
        }
        
        private ICustomers _customers;
        
        public virtual ICustomers Customers
        {
            get { return this._customers; }
        }
        
        private IEmployees _employees;
        
        public virtual IEmployees Employees
        {
            get { return this._employees; }
        }
        
        private IEnrollments _enrollments;
        
        public virtual IEnrollments Enrollments
        {
            get { return this._enrollments; }
        }
        
        private IOrders _orders;
        
        public virtual IOrders Orders
        {
            get { return this._orders; }
        }
        
        private ISetup _setup;
        
        public virtual ISetup Setup
        {
            get { return this._setup; }
        }
        
        private IStudents _students;
        
        public virtual IStudents Students
        {
            get { return this._students; }
        }
        
        /// <summary>
        /// Initializes a new instance of the XamarinMVVMSampleWebAPI class.
        /// </summary>
        public XamarinMVVMSampleWebAPIService()
            : base()
        {
            this._courses = new Courses(this);
            this._customers = new Customers(this);
            this._employees = new Employees(this);
            this._enrollments = new Enrollments(this);
            this._orders = new Orders(this);
            this._setup = new Setup(this);
            this._students = new Students(this);
            this._baseUri = new Uri("https://xamarinmvvmsamplewebapi.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the XamarinMVVMSampleWebAPI class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public XamarinMVVMSampleWebAPIService(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._courses = new Courses(this);
            this._customers = new Customers(this);
            this._employees = new Employees(this);
            this._enrollments = new Enrollments(this);
            this._orders = new Orders(this);
            this._setup = new Setup(this);
            this._students = new Students(this);
            this._baseUri = new Uri("https://xamarinmvvmsamplewebapi.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the XamarinMVVMSampleWebAPI class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public XamarinMVVMSampleWebAPIService(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._courses = new Courses(this);
            this._customers = new Customers(this);
            this._employees = new Employees(this);
            this._enrollments = new Enrollments(this);
            this._orders = new Orders(this);
            this._setup = new Setup(this);
            this._students = new Students(this);
            this._baseUri = new Uri("https://xamarinmvvmsamplewebapi.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the XamarinMVVMSampleWebAPI class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public XamarinMVVMSampleWebAPIService(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the XamarinMVVMSampleWebAPI class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public XamarinMVVMSampleWebAPIService(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the XamarinMVVMSampleWebAPI class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public XamarinMVVMSampleWebAPIService(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
