// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using XamFormsMvvmAndRESTServices.Models;

namespace XamFormsMvvmAndRESTServices.Models
{
    public static partial class CourseCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Course> DeserializeJson(JToken inputObject)
        {
            IList<Course> deserializedObject = new List<Course>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Course course = new Course();
                course.DeserializeJson(iListValue);
                deserializedObject.Add(course);
            }
            return deserializedObject;
        }
    }
}
